import { AnimationType } from "@/lib/types";

export type ArrowDirection = "up" | "down" | "out" | "in" | "back" | "none";

export const arrowDirection: Record<AnimationType, ArrowDirection> = {
  pushup: "down",
  "press-horizontal": "up",
  fly: "in",
  pullover: "in",
  pulldown: "down",
  row: "back",
  "press-overhead": "up",
  "raise-lateral": "out",
  "raise-front": "up",
  "upright-row": "up",
  "face-pull": "back",
  shrug: "up",
  curl: "up",
  "curl-unilateral": "up",
  dip: "down",
  "extension-triceps": "up",
  pushdown: "down",
  kickback: "back",
  squat: "down",
  "leg-press": "none",
  legcurl: "none",
  "leg-extension": "up",
  "calf-raise": "up",
  stretch: "none",
  plank: "none",
  "leg-raise": "up",
  "knee-tuck": "in",
  "reverse-crunch": "in",
  crunch: "in",
  "cable-crunch": "in",
  "high-knees": "none",
  jump: "up",
  walk: "none",
};
